[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "geoipsets"
version = "2.4.0"
license = {text = "GPLv3"}
description = "Utility to build country-specific IP sets for ipset/iptables and nftables."
classifiers = [
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
urls = {Homepage = "https://github.com/chr0mag/geoipsets"}
dependencies = ["requests", "beautifulsoup4"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.scripts]
geoipsets = "geoipsets.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests"]
namespaces = false
