[Service]
ExecStart=/usr/bin/ipset flush CN.ipv4
ExecStart=/usr/bin/ipset restore --exist --file /var/local/geoipsets/dbip/ipset/ipv4/CN.ipv4
ExecStart=/usr/bin/ipset flush CN.ipv6
ExecStart=/usr/bin/ipset restore --exist --file /var/local/geoipsets/dbip/ipset/ipv6/CN.ipv6
ExecStart=/usr/bin/ipset save --file /etc/ipset/ipset.conf
